import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getPostsForTopPage } from '../../../lib/notionAPI'
import SinglePost from '../../../components/Post/SinglePost'
import { GetStaticPaths, GetStaticProps } from 'next'

export const getStaticPaths: GetStaticPaths = async () => {
  return {
    paths: [{ params: { page: '1' } }, { params: { page: '2' } }],
    fallback: 'blocking',
  }
}

export const getStaticProps: GetStaticProps = async () => {
  const fourPosts = await getPostsForTopPage()

  return {
    props: {
      fourPosts: fourPosts,
    },
    revalidate: 60 * 60 * 6, // 6時間ごとに更新
  }
}

const BlogPageList = ({ fourPosts }) => {
  return (
    <div className="container h-full w-full mx-auto">
      <Head>
        <title>Notion Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container w-full mt-16">
        <h1 className="text-5xl font-medium text-center mb-16">
          Notion Blog🚀
        </h1>
        <section className="sm:grid grid-cols-2 w-5/6 gap-3 mx-auto">
          {fourPosts.map((post) => (
            <div>
              <SinglePost
                title={post.title}
                description={post.description}
                date={post.date}
                tags={post.tags}
                slug={post.slug}
                isPaginationPage={true}
              />
            </div>
          ))}
        </section>
      </main>
    </div>
  )
}

export default BlogPageList
